# Development environment HQ MIR ID Controller API Service
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
version: "3.5"
services:
  postgresql:
    image: postgres
    environment:
      - POSTGRES_DB=devdatabase
      - POSTGRES_USER=devusername
      - POSTGRES_PASSWORD=devpassword
    ports:
      - "5431:5432"
  redis:
    image: redis:4.0.8-alpine
    ports:
        - "6379:6379"
#  controller:
#    container_name: test_apr
#    image: identifiersorg/cloud-hq-ws-mirid-controller:test
#    environment:
#      - HQ_WS_MIRID_CONTROLLER_CONFIG_APPLICATION_ACTIVE_PROFILE=authdisabled
#      - HQ_WS_MIRID_CONTROLLER_CONFIG_REDIS_HOST=redis
#      - HQ_WS_MIRID_CONTROLLER_CONFIG_JDBC_URL=jdbc:postgresql://postgresql:5432/devdatabase
#    ports:
#      - "8181:8181"
networks:
  default:
    name: idorg-dev-hq-mirid-controller
#    driver: none
